# Generated by Django 4.2.6 on 2023-12-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_registration_model',
            name='repassword',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
    ]
