# Generated by Django 5.0 on 2023-12-13 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0002_owner_registration_model_repassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='bed_details_model',
            fields=[
                ('bed_id', models.AutoField(primary_key=True, serialize=False)),
                ('bed_no', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('bed_cost', models.PositiveIntegerField()),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='comments_model',
            fields=[
                ('comments_id', models.AutoField(primary_key=True, serialize=False)),
                ('hostel_id', models.PositiveIntegerField()),
                ('comments', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='gallery_model',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('hostel_id', models.PositiveIntegerField()),
                ('images', models.ImageField(upload_to='hostel/')),
            ],
        ),
        migrations.CreateModel(
            name='hostel_details_model',
            fields=[
                ('hostel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(max_length=100)),
                ('GST', models.CharField(max_length=15, unique=True)),
                ('license', models.CharField(max_length=20, unique=True)),
                ('type_of_hostel', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Co_living', 'Co_living')], max_length=10)),
                ('hostel_owner_name', models.CharField(max_length=30)),
                ('owner_id', models.PositiveIntegerField()),
                ('owner_phone_no', models.PositiveBigIntegerField(unique=True)),
                ('owner_email', models.EmailField(max_length=254, unique=True)),
                ('vaccancy', models.PositiveBigIntegerField()),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='occupied_details_model',
            fields=[
                ('occ_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone_no', models.PositiveBigIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('others', 'others')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhaar', models.PositiveBigIntegerField()),
                ('image', models.ImageField(null=True, upload_to='profile/')),
                ('bed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.bed_details_model')),
            ],
        ),
        migrations.CreateModel(
            name='rooms_details_model',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_no', models.PositiveIntegerField()),
                ('num_of_beds', models.PositiveIntegerField()),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.hostel_details_model')),
            ],
        ),
        migrations.AddField(
            model_name='bed_details_model',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.rooms_details_model'),
        ),
    ]
